name: go1

# Proprioceptive observations. Noise specified is added during data
# augmentation during pretraining.
proprio_obs:
  types:
    - name: base_lin_vel
      dim: 3
      noise: 0.05
    - name: base_ang_vel
      dim: 3
      noise: 0.1
    - name: projected_gravity
      dim: 3
      noise: 0.025
    - name: joint_pos
      dim: 12
      noise: 0.01
    - name: joint_vel
      dim: 12
      noise: 0.75
    - name: cos_sin_phase
      dim: 2
      noise: 0.001

# Exteroceptive observations. Noise specified is added during data
# augmentation during pretraining.
extero_obs:
  types:
    - name: height_scan
      dim: [21, 15]
      noise: 0.02

# Command to the robot.
cmd:
  dim: 3

# Action space. Noise specified is added during data generation. 
actions:
  - name: FR_hip_joint
    min_noise: 0.05
    max_noise: 2.5
  - name: FR_thigh_joint
    min_noise: 0.05
    max_noise: 2.5
  - name: FR_calf_joint
    min_noise: 0.05
    max_noise: 2.5
  - name: FL_hip_joint
    min_noise: 0.05
    max_noise: 2.5
  - name: FL_thigh_joint
    min_noise: 0.05
    max_noise: 2.5
  - name: FL_calf_joint
    min_noise: 0.05
    max_noise: 2.5
  - name: RR_hip_joint
    min_noise: 0.05
    max_noise: 2.5
  - name: RR_thigh_joint
    min_noise: 0.05
    max_noise: 2.5
  - name: RR_calf_joint 
    min_noise: 0.05
    max_noise: 2.5
  - name: RL_hip_joint
    min_noise: 0.05
    max_noise: 2.5
  - name: RL_thigh_joint
    min_noise: 0.05
    max_noise: 2.5
  - name: RL_calf_joint
    min_noise: 0.05
    max_noise: 2.5